import BlackModal from '../components/common/Modal/BlackModal';
import theme from './theme';
//console.log('t', theme);
const whiteColors = {
  background: 'white',
  categorytext: 'black',
  modalbackground: 'white',
  tag: 'black',
  taghover: theme.primary,
  keywordtag: 'black',
  settingbtn: 'white',
  settingbtnbg: theme.gray,
  topbg: theme.lightGray,
  cardbody: 'white',
  cardsub: theme.darkGray,
  bodybg: 'white',
  swiperafter: 'black',
  footercontent: 'none',
  sortbg: theme.lightGray,
  setting: theme.lightGray,
  inputTxt: theme.darkGray,
  camera: 'white',
  settingtxt: theme.darkGray,
  backbtn: 'invert(0)',
  loginbg: 'white',
  highlight:
    'linear-gradient( 180deg, transparent 0%, transparent 20%, #2cff2c 20%, #2cff2c 55%, transparent 55%, transparent 100% )',
  inputline: theme.lightGray,
  formbox: 'white',
  placeholder: theme.gray,
  roundbtn: '1px solid black',
  boxShadow: '0 0 0 2px #f3f3f3',
};
const darkColors = {
  background: 'black',
  categorytext: 'white',
  modalbackground: theme.darkBg2,
  tag: theme.primary,
  taghover: 'white',
  keywordtag: theme.primary,
  settingbtn: 'white',
  settingbtnbg: theme.darkGray,
  topbg: theme.darkBg2,
  cardbody: theme.darkBg,
  cardsub: theme.gray,
  bodybg: theme.darkBg,
  swiperafter: theme.lightGray,
  footercontent: 'opacity(0.5)',
  sortbg: theme.primary,
  setting: theme.keyWordGray,
  inputTxt: 'white',
  camera: theme.keyWordGray,
  settingtxt: theme.primary,
  backbtn: 'invert(1)',
  loginbg: 'rgba(0,0,0,0.8)',
  highlight: 'none',
  inputline: theme.keyWordGray,
  formbox: theme.darkGray,
  placeholder: theme.lightGray,
  roundbtn: '1px solid #f3f3f3',
  boxshadow: 'none',
};

export { whiteColors, darkColors };
