import theme from './theme';
//console.log('t', theme);
const whiteColors = {
  background: 'white',
  categorytext: 'black',
  modalbackground: 'white',
  tag: 'black',
  taghover: theme.primary,
  keywordtag: 'black',
  settingbtn: 'white',
  settingbtnbg: theme.gray,
  topbg: theme.lightGray,
  cardbody: 'white',
  cardsub: theme.darkGray,
  bodybg: 'white',
  swiperafter: 'black',
  footercontent: 'none',
  sortbg: theme.lightGray,
  setting: theme.lightGray,
  inputTxt: theme.darkGray,
  camera: 'white',
  settingtxt: theme.darkGray,
  backbtn: 'invert(0)',
};
const darkColors = {
  background: 'black',
  categorytext: 'white',
  modalbackground: theme.darkBg2,
  tag: theme.primary,
  taghover: 'white',
  keywordtag: theme.primary,
  settingbtn: 'white',
  settingbtnbg: theme.darkGray,
  topbg: theme.darkBg2,
  cardbody: theme.darkBg,
  cardsub: theme.gray,
  bodybg: theme.darkBg,
  swiperafter: theme.lightGray,
  footercontent: 'opacity(0.5)',
  sortbg: theme.primary,
  setting: theme.keyWordGray,
  inputTxt: 'white',
  camera: theme.keyWordGray,
  settingtxt: theme.primary,
  backbtn: 'invert(1)',
};

export { whiteColors, darkColors };
